/* APP_SERVICE_CONFIG */
docker_registry_server_url = "https://devbsai.azurecr.io"
docker_registry_server_username = "devbsai"
docker_registry_server_password = "lh9Do7/2HFEkuyvUBPVDYJH9sCYXRuOF"
docker_custom_image_name_app_service1 = "devbsai.azurecr.io/voxelbox:new"
linux_fx_version_app_service1 = "DOCKER|devbsai.azurecr.io/voxelbox:new"
app_storage_key_1  = "oeJ6/JQaRKiFfO2bSmTutT7wA3MHbxVb+Um4J7Eu6LZ38Cawdq7jTewUum8emaruohx8N+RKdiSky0jo5sbPAw=="
/* APP_SERVICE-2 */
docker_custom_image_name_app_service2 = "devbsai.azurecr.io/voxelboxplusgliomaecm:latest"
linux_fx_version_app_service2 = "DOCKER|devbsai.azurecr.io/voxelboxplusgliomaecm:latest"
/* APP_SERVICE-3 */
docker_custom_image_name_app_service3 = "devbsai.azurecr.io/uploadfile:latest"
linux_fx_version_app_service3 = "DOCKER|devbsai.azurecr.io/uploadfile:latest"
/* APP_SERVICE-4 */
docker_custom_image_name_app_service4 = "devbsai.azurecr.io/file_processsing:medidata"
linux_fx_version_app_service4 = "DOCKER|devbsai.azurecr.io/file_processsing:medidata_prod"
/* APP_SERVICE-5 */
docker_custom_image_name_app_service5 = "devbsai.azurecr.io/voxelbox_smri_cloud:latest"
linux_fx_version_app_service5 = "DOCKER|devbsai.azurecr.io/voxelbox_smri_cloud:latest"
/* APP_SERVICE-6 */
docker_custom_image_name_app_service6 = "devbsai.azurecr.io/voxelbox_dti:latest"
linux_fx_version_app_service6 = "DOCKER|devbsai.azurecr.io/voxelbox_dti:latest"
/* APP_SERVICE-8 */
docker_custom_image_name_app_service8 = "devbsai.azurecr.io/voxelbox-fc:new"
linux_fx_version_app_service8 = "DOCKER|devbsai.azurecr.io/voxelbox-fc:new1"
/* APP_SERVICE-9 */
docker_custom_image_name_app_service9 = "devbsai.azurecr.io/voxelbox-dementia:latest"
linux_fx_version_app_service9 = "DOCKER|devbsai.azurecr.io/voxelbox-dementia:latest"
/* APP_SERVICE-10 */
docker_custom_image_name_app_service10 = "devbsai.azurecr.io/datafile_testing:latest"
linux_fx_version_app_service10 = "DOCKER|devbsai.azurecr.io/file_processsing:medidatainn_gct"
/* APP_SERVICE-11 */
docker_custom_image_name_app_service11 = "devbsai.azurecr.io/datafile_testing:latest"
linux_fx_version_app_service11 = "DOCKER|devbsai.azurecr.io/file_processsing:carpel"
/* APP_SERVICE-12 */
docker_custom_image_name_app_service12 = "devbsai.azurecr.io/normative_mapping:latest"
linux_fx_version_app_service12 = "DOCKER|devbsai.azurecr.io/normative_mapping:latest"
/* APP_SERVICE-13 */
docker_custom_image_name_app_service13 = "devbsai.azurecr.io/voxelbox:innovate"
linux_fx_version_app_service13 = "DOCKER|devbsai.azurecr.io/voxelbox:innovate"
/* APP_SERVICE-14 */
docker_custom_image_name_app_service14 = "devbsai.azurecr.io/medidata-final"
linux_fx_version_app_service14 = "DOCKER|devbsai.azurecr.io/voxelbox:new"
/* APP_SERVICE-15 */
docker_custom_image_name_app_service15 = "devbsai.azurecr.io/voxelbox-fc"
linux_fx_version_app_service15 = "DOCKER|devbsai.azurecr.io/voxelbox-fc:medidata-gct"
/* APP_SERVICE-16 */
docker_custom_image_name_app_service16 = "devbsai.azurecr.io/voxelbox-nmli"
linux_fx_version_app_service16 = "DOCKER|devbsai.azurecr.io/voxelbox-nmli:medidata-gct"

#/* ACI */
#docker_registry_server_url_aci = "devbsai.azurecr.io"
#aci_storage_key = "aSQyQNQ1mkE4Vuv+G+4gmXh0gamTa1smZcXwIuzDhLLz71PhhSH/LMepGpQ+KSswV3pHiZ3gdj5NbdetPKcj2Q=="


# terraform.tfvars
appId         = "32521498-0df8-4e73-b157-33bdd70ddfd2"
client_secret = "Bg4uNiMW4--Vj13lD6NXB2qHjEQ78ioOBk"
