/* APP_SERVICE_CONFIG */
docker_registry_server_url = "https://devbsai.azurecr.io"
docker_registry_server_username = "devbsai"
docker_registry_server_password = "lh9Do7/2HFEkuyvUBPVDYJH9sCYXRuOF"
docker_custom_image_name_1_app_service1 = "devbsai.azurecr.io/voxelbox:v0.7"
linux_fx_version_1_app_service1 = "DOCKER|devbsai.azurecr.io/voxelbox:latest"
app_storage_key_1 = "aSQyQNQ1mkE4Vuv+G+4gmXh0gamTa1smZcXwIuzDhLLz71PhhSH/LMepGpQ+KSswV3pHiZ3gdj5NbdetPKcj2Q=="
docker_registry_server_url_aci = "devbsai.azurecr.io"
aci_storage_key = "aSQyQNQ1mkE4Vuv+G+4gmXh0gamTa1smZcXwIuzDhLLz71PhhSH/LMepGpQ+KSswV3pHiZ3gdj5NbdetPKcj2Q=="